<template>
  <accountShell title="团队空间" eyebrow="一起创作" description="个人资产默认私有。需要共享时，主动上传一份副本到团队空间。">
    <template #actions><uiButton variant="secondary" :loading="loading" @click="loadTeams">刷新团队</uiButton><uiButton @click="createVisible = true">创建团队</uiButton></template>
    <p v-if="errorMessage" class="pageError" role="alert">{{ errorMessage }}</p>
    <div v-if="auth.teams.length" class="teamWorkspace">
      <div class="teamHeader"><uiSelect :modelValue="auth.currentTeamId" :options="teamOptions" class="teamSelect" aria-label="当前团队" @update:modelValue="value => typeof value === 'string' && auth.selectTeam(value)" /><span class="teamRole">{{ currentTeam?.role === 'owner' ? '团队 owner' : currentTeam?.role === 'root' ? 'root 管理员' : '团队成员' }}</span><div class="teamActions"><uiButton v-if="canManage" variant="ghost" :disabled="busy" @click="renameTeam">重命名团队</uiButton><uiButton v-if="canManage && currentTeam?.status !== 'archived'" variant="danger" :disabled="busy" @click="archiveTeam">解散团队</uiButton><uiButton v-if="auth.isRoot && currentTeam?.status === 'archived'" variant="secondary" :disabled="busy" @click="restoreTeam">恢复团队</uiButton><uiButton v-if="currentTeam?.role === 'member'" variant="ghost" :disabled="busy" @click="leaveTeam">退出团队</uiButton></div></div>
      <uiTabs :modelValue="activeTab" :options="tabs" label="团队内容" @update:modelValue="value => typeof value === 'string' && (activeTab = value)">
        <section v-if="activeTab === 'assets'" class="teamAssets">
          <header class="sectionHeader"><div><h2>团队共享资产</h2><p>上传生成独立副本，个人原件不会移动或删除。</p></div><uiButton :disabled="busy || currentTeam?.status === 'archived'" :loading="busy" @click="fileInput?.click()">上传资产</uiButton><input ref="fileInput" class="fileInput" type="file" multiple @change="uploadFiles" /></header>
          <p v-if="currentTeam?.status === 'archived'" class="sectionHint">团队已解散。root 可以查看归档资产，恢复团队后成员可重新使用。</p>
          <uiTable :rows="assets" :columns="assetColumns" :loading="detailLoading" emptyText="团队还没有共享资产" label="团队资产"><template #cell="{ row, column }"><button v-if="column.key === 'name'" type="button" class="assetName" @click="previewAsset = row as TeamAsset"><icon-file :size="18" aria-hidden="true" /><span>{{ row.name }}</span></button><span v-else-if="column.key === 'bytes'">{{ formatBytes(Number(row.bytes)) }}</span><span v-else-if="column.key === 'uploadedBy'">{{ memberName(String(row.uploadedBy)) }}</span><div v-else-if="column.key === 'actions'" class="rowActions"><uiButton variant="ghost" size="small" :disabled="busy" @click="downloadAsset(row as TeamAsset)">下载</uiButton><uiButton variant="ghost" size="small" :disabled="busy" @click="copyToLibrary(row as TeamAsset)">复制到我的素材库</uiButton><uiButton variant="ghost" size="small" :disabled="busy || !workspace.project" @click="copyToProject(row as TeamAsset)">复制到当前项目</uiButton><uiButton v-if="canManage" variant="ghost" size="small" :disabled="busy" @click="renameAsset(row as TeamAsset)">重命名</uiButton><uiButton v-if="canManage" variant="danger" size="small" :disabled="busy" @click="deleteAsset(row as TeamAsset)">删除</uiButton></div><span v-else>{{ row[column.key] }}</span></template></uiTable>
        </section>
        <section v-else class="teamMembers"><header class="sectionHeader"><div><h2>团队成员</h2><p>成员积分独立，可在同团队成员之间自由划转。</p></div><uiButton v-if="canManage && currentTeam?.status !== 'archived'" variant="secondary" :disabled="busy" @click="inviteVisible = true">邀请成员</uiButton></header><uiTable :rows="members" :columns="memberColumns" :loading="detailLoading" emptyText="暂时没有成员" label="团队成员"><template #cell="{ row, column }"><span v-if="column.key === 'role'">{{ row.role === 'owner' ? 'owner' : '成员' }}</span><span v-else-if="column.key === 'status'">{{ row.status === 'active' ? '正常' : '已停用' }}</span><uiButton v-else-if="column.key === 'actions' && canManage && row.id !== currentTeam?.ownerUserId" variant="danger" size="small" :disabled="busy" @click="removeTeamUser(row as TeamMember)">移除成员</uiButton><span v-else>{{ row[column.key] ?? '' }}</span></template></uiTable><router-link class="transferLink" to="/account">前往个人账户划转积分 →</router-link></section>
      </uiTabs>
    </div>
    <div v-else-if="!loading" class="emptyTeam"><icon-users-group :size="36" aria-hidden="true" /><h2>还没有加入团队</h2><p>创建一个团队，或通过其他成员发送的邀请链接加入。</p><uiButton @click="createVisible = true">创建你的团队</uiButton></div>
    <uiDialog v-model="createVisible" title="创建团队" :width="460" :closeOnClickModal="!busy"><uiForm class="dialogForm" :model="createForm" :rules="createRules" :disabled="busy" @submit="submitCreate"><uiFormField prop="name" label="团队名称" required><template #default="{ id, describedBy, invalid, required }"><uiInput :id="id" v-model.trim="createForm.name" maxlength="160" autofocus :aria-describedby="describedBy" :error="invalid" :required="required" :disabled="busy" /></template></uiFormField><p class="sectionHint">创建后你将成为 owner，负责管理团队成员和共享资产。</p><p v-if="dialogError" class="pageError" role="alert">{{ dialogError }}</p><uiButton htmlType="submit" :loading="busy" :disabled="busy">创建团队</uiButton></uiForm></uiDialog>
    <uiDialog v-model="inviteVisible" title="邀请团队成员" :width="520" :closeOnClickModal="!busy"><uiForm class="dialogForm" :model="inviteForm" :rules="inviteRules" :disabled="busy" @submit="submitInvite"><uiFormField prop="email" label="成员邮箱" required><template #default="{ id, describedBy, invalid, required }"><uiInput :id="id" v-model.trim="inviteForm.email" type="email" autocomplete="email" :aria-describedby="describedBy" :error="invalid" :required="required" :disabled="busy" /></template></uiFormField><p class="sectionHint">邀请有效期 7 天。未注册的成员可通过链接创建账户并加入团队。</p><p v-if="dialogError" class="pageError" role="alert">{{ dialogError }}</p><uiButton htmlType="submit" :loading="busy" :disabled="busy">生成邀请链接</uiButton></uiForm><div v-if="inviteLink" class="inviteResult"><uiInput :modelValue="inviteLink" readonly aria-label="邀请链接" /><uiButton variant="secondary" @click="copyInvitation">复制邀请链接</uiButton></div></uiDialog>
    <uiDialog :modelValue="!!previewAsset" :title="previewAsset?.name ?? '团队资产'" width="min(900px, calc(100vw - 32px))" @update:modelValue="value => !value && (previewAsset = undefined)"><uiImage v-if="previewAsset?.mimeType.startsWith('image/')" :src="assetUrl(previewAsset.id)" :alt="previewAsset.name" fit="contain" /><uiMediaPlayer v-else-if="previewAsset?.mimeType.startsWith('video/') || previewAsset?.mimeType.startsWith('audio/')" :src="assetUrl(previewAsset.id)" :kind="previewAsset.mimeType.startsWith('audio/') ? 'audio' : 'video'" :label="previewAsset.name" /><p v-else class="sectionHint">此文件可下载后打开。</p><template #footer><uiButton v-if="previewAsset" variant="secondary" @click="downloadAsset(previewAsset)">下载资产</uiButton></template></uiDialog>
  </accountShell>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from "vue";
import axios from "axios";
import { uiButton, uiDialog, uiForm, uiFormField, uiInput, uiSelect, uiTabs, uiTable, uiImage, uiMediaPlayer, useUiFeedback, isUiCancelledError, type UiColumn, type UiFormRules } from "@omnistudio-next/ui";
import accountShell from "@/components/account/accountShell.vue";
import { useAuthStore } from "@/stores/auth";
import { useWorkspaceStore } from "@/stores/workspace";
import { authClient } from "@/lib/authApi";
import { getMembers, getTeamAssets, createTeam, inviteMember, removeMember, saveTeam, uploadTeamFile, renameTeamAsset, removeTeamAsset, importTeamAsset, type TeamAsset, type TeamMember } from "@/lib/accountApi";
import saveFile from "@/lib/saveFile";
import { writeClipboardText } from "@/lib/clipboard";
const auth = useAuthStore(); const workspace = useWorkspaceStore(); const feedback = useUiFeedback();
const loading = ref(false); const detailLoading = ref(false); const busy = ref(false); const errorMessage = ref(""); const dialogError = ref(""); let detailRevision = 0;
const members = ref<TeamMember[]>([]); const assets = ref<TeamAsset[]>([]); const activeTab = ref("assets"); const tabs = [{ value: "assets", label: "共享资产" }, { value: "members", label: "成员" }];
const createVisible = ref(false); const inviteVisible = ref(false); const createForm = reactive({ name: "" }); const inviteForm = reactive({ email: "" }); const inviteLink = ref(""); const fileInput = ref<HTMLInputElement>(); const previewAsset = ref<TeamAsset>();
const createRules: UiFormRules = { name: { required: true, whitespace: true, message: "请输入团队名称" } };
const inviteRules: UiFormRules = { email: [{ required: true, message: "请输入成员邮箱" }, { type: "email", message: "请输入有效的邮箱地址" }] };
const currentTeam = computed(() => auth.currentTeam); const canManage = computed(() => auth.isRoot || currentTeam.value?.ownerUserId === auth.user?.id);
const teamOptions = computed(() => auth.teams.map(team => ({ value: team.id, label: team.name + (team.status === "archived" ? " · 已解散" : "") })));
const assetColumns: UiColumn[] = [{ key: "name", label: "名称" }, { key: "bytes", label: "大小", width: 100 }, { key: "uploadedBy", label: "上传成员", width: 140 }, { key: "actions", label: "操作", width: 360, align: "right" }];
const memberColumns: UiColumn[] = [{ key: "displayName", label: "成员" }, { key: "email", label: "邮箱" }, { key: "role", label: "角色", width: 100 }, { key: "status", label: "状态", width: 100 }, { key: "actions", label: "操作", width: 120, align: "right" }];
function errorText(error: unknown) { return axios.isAxiosError(error) ? error.response?.data?.message || "连接中断，请刷新后确认结果" : error instanceof Error ? error.message : "操作失败，请重试"; }
function assetUrl(id: string) { return `/api/account/teamAssets/read?id=${encodeURIComponent(id)}`; }
function formatBytes(bytes: number) { return bytes < 1024 ? `${bytes} B` : bytes < 1048576 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1048576).toFixed(1)} MB`; }
function memberName(id: string) { return members.value.find(member => member.id === id)?.displayName ?? (id === auth.user?.id ? auth.user.displayName : "原团队成员"); }
async function loadTeams() { loading.value = true; errorMessage.value = ""; try { await auth.restoreSession(); await loadDetail(); } catch (error) { errorMessage.value = errorText(error); } finally { loading.value = false; } }
async function loadDetail() { const id = auth.currentTeamId; const revision = ++detailRevision; members.value = []; assets.value = []; if (!id) return; detailLoading.value = true; try { const [people, files] = await Promise.all([getMembers(id), getTeamAssets(id)]); if (revision === detailRevision) { members.value = people; assets.value = files.assets; } } catch (error) { if (revision === detailRevision) errorMessage.value = errorText(error); } finally { if (revision === detailRevision) detailLoading.value = false; } }
watch(() => auth.currentTeamId, () => { inviteLink.value = ""; previewAsset.value = undefined; errorMessage.value = ""; void loadDetail(); });
watch([createVisible, inviteVisible], () => { dialogError.value = ""; });
async function submitCreate() { busy.value = true; dialogError.value = ""; try { const team = await createTeam(createForm.name); await auth.restoreSession(); auth.selectTeam(team.id); createForm.name = ""; createVisible.value = false; await loadDetail(); } catch (error) { dialogError.value = errorText(error); } finally { busy.value = false; } }
async function submitInvite() { const id = auth.currentTeamId; busy.value = true; dialogError.value = ""; try { const invitation = await inviteMember(id, inviteForm.email); const url = new URL(location.href); url.search = ""; url.hash = `/auth/invite?token=${encodeURIComponent(invitation.token)}`; inviteLink.value = url.href; } catch (error) { dialogError.value = errorText(error); } finally { busy.value = false; } }
async function copyInvitation() { try { await writeClipboardText(inviteLink.value); feedback.message({ tone: "success", message: "邀请链接已复制" }); } catch (error) { dialogError.value = errorText(error); } }
async function uploadFiles(event: Event) { const input = event.target as HTMLInputElement; const files = [...input.files ?? []]; const id = auth.currentTeamId; busy.value = true; errorMessage.value = ""; try { for (const file of files) await uploadTeamFile(id, file); await loadDetail(); } catch (error) { errorMessage.value = errorText(error); await loadDetail(); } finally { input.value = ""; busy.value = false; } }
async function downloadAsset(asset: TeamAsset) { try { await saveFile(() => authClient.get<Blob>(assetUrl(asset.id), { responseType: "blob" }).then(response => response.data), asset.name); } catch (error) { errorMessage.value = errorText(error); } }
async function copyToProject(asset: TeamAsset) { const project = workspace.project; if (!project) return; busy.value = true; try { await importTeamAsset(asset.id, project.directory); feedback.message({ tone: "success", message: `已复制到项目「${project.name}」` }); window.dispatchEvent(new Event("omnistudio-next:team-asset-imported")); } catch (error) { errorMessage.value = errorText(error); } finally { busy.value = false; } }
async function copyToLibrary(asset: TeamAsset) { busy.value = true; try { await importTeamAsset(asset.id); feedback.message({ tone: "success", message: "已复制到个人素材库" }); } catch (error) { errorMessage.value = errorText(error); } finally { busy.value = false; } }
async function renameAsset(asset: TeamAsset) { try { const result = await feedback.prompt("资产名称", "重命名团队资产", { inputValue: asset.name, inputValidator: value => !!value?.trim() || "请输入名称", confirmButtonText: "保存名称", cancelButtonText: "取消" }); busy.value = true; await renameTeamAsset(asset.id, result.value.trim()); await loadDetail(); } catch (error) { if (!isUiCancelledError(error)) errorMessage.value = errorText(error); } finally { busy.value = false; } }
async function deleteAsset(asset: TeamAsset) { try { await feedback.confirm(`删除团队共享副本「${asset.name}」？所有成员将无法再访问这个副本，个人原件不受影响。`, "删除团队资产", { danger: true, confirmButtonText: "删除共享副本", cancelButtonText: "保留资产" }); busy.value = true; await removeTeamAsset(asset.id); await loadDetail(); } catch (error) { if (!isUiCancelledError(error)) errorMessage.value = errorText(error); } finally { busy.value = false; } }
async function removeTeamUser(member: TeamMember) { const id = auth.currentTeamId; try { await feedback.confirm(`移除 ${member.displayName}（${member.email}）？对方将失去团队共享资产访问权，已上传的团队副本会保留。`, "移除团队成员", { danger: true, confirmButtonText: "移除成员", cancelButtonText: "保留成员" }); busy.value = true; await removeMember(id, member.id); await loadDetail(); } catch (error) { if (!isUiCancelledError(error)) errorMessage.value = errorText(error); } finally { busy.value = false; } }
async function renameTeam() { const team = currentTeam.value; if (!team) return; try { const result = await feedback.prompt("团队名称", "重命名团队", { inputValue: team.name, inputValidator: value => !!value?.trim() || "请输入名称", confirmButtonText: "保存名称", cancelButtonText: "取消" }); busy.value = true; await saveTeam(team.id, { name: result.value.trim() }); await loadTeams(); } catch (error) { if (!isUiCancelledError(error)) errorMessage.value = errorText(error); } finally { busy.value = false; } }
async function archiveTeam() { const team = currentTeam.value; if (!team) return; try { await feedback.confirm(`解散「${team.name}」？成员将失去共享资产访问权，团队资产会保留归档，个人资产和积分不受影响。`, "解散团队", { danger: true, confirmButtonText: "解散团队", cancelButtonText: "保留团队" }); busy.value = true; await saveTeam(team.id, { archive: true }); await loadTeams(); } catch (error) { if (!isUiCancelledError(error)) errorMessage.value = errorText(error); } finally { busy.value = false; } }
async function restoreTeam() { const team = currentTeam.value; if (!team) return; busy.value = true; try { await saveTeam(team.id, { restore: true }); await loadTeams(); } catch (error) { errorMessage.value = errorText(error); } finally { busy.value = false; } }
async function leaveTeam() { const team = currentTeam.value; const user = auth.user; if (!team || !user) return; try { await feedback.confirm(`退出「${team.name}」？你将无法继续访问团队共享资产，个人项目和积分仍保留。`, "退出团队", { confirmButtonText: "退出团队", cancelButtonText: "留在团队" }); busy.value = true; await removeMember(team.id, user.id); await loadTeams(); } catch (error) { if (!isUiCancelledError(error)) errorMessage.value = errorText(error); } finally { busy.value = false; } }
onMounted(loadTeams);
</script>

<style lang="scss" scoped>
.pageError { color: var(--uiStatusError); margin: 0 0 20px; font-size: var(--uiFontControl); line-height: 1.6; overflow-wrap: anywhere; }
.teamWorkspace { .teamHeader { display: flex; align-items: center; gap: 16px; flex-wrap: wrap; margin-bottom: 24px; .teamSelect { width: min(360px, 100%); } .teamRole { color: var(--uiTextMuted); font-size: 12px; } .teamActions { display: flex; gap: 8px; flex-wrap: wrap; margin-left: auto; } } .teamAssets, .teamMembers { min-width: 0; .sectionHeader { display: flex; align-items: flex-start; justify-content: space-between; gap: 20px; margin: 8px 0 24px; h2 { font-size: 18px; margin: 0 0 8px; } p { margin: 0; color: var(--uiTextMuted); font-size: var(--uiFontControl); line-height: 1.7; } .fileInput { display: none; } } .assetName { display: flex; gap: 10px; align-items: center; padding: 0; border: 0; color: var(--uiTextPrimary); background: transparent; font: inherit; cursor: pointer; text-align: left; span { overflow-wrap: anywhere; } svg { flex-shrink: 0; color: var(--uiTextMuted); } } .rowActions { display: flex; gap: 4px; justify-content: flex-end; flex-wrap: wrap; } .transferLink { display: inline-block; margin-top: 20px; color: var(--uiActionPrimary); font-size: var(--uiFontControl); text-decoration: none; } } }
.sectionHint { color: var(--uiTextMuted); font-size: var(--uiFontControl); line-height: 1.7; }
.emptyTeam { display: grid; justify-items: start; gap: 16px; padding: 36px 0; color: var(--uiTextMuted); h2 { margin: 0; color: var(--uiTextPrimary); font-size: 20px; } p { margin: 0; line-height: 1.7; } }
.dialogForm { display: grid; gap: 20px; .sectionHint { margin: 0; } }
.inviteResult { display: grid; gap: 12px; border-top: 1px solid var(--uiBorderDefault); padding-top: 24px; margin-top: 24px; }
@media (max-width: 700px) { .teamWorkspace { .teamHeader .teamActions { margin-left: 0; width: 100%; } .teamAssets .sectionHeader, .teamMembers .sectionHeader { flex-direction: column; } } }
</style>
