import type { Express } from "express";

import route1 from "./routes/account/teamAssets/copy";
import route2 from "./routes/account/teamAssets/import";
import route3 from "./routes/account/teamAssets/list";
import route4 from "./routes/account/teamAssets/read";
import route5 from "./routes/account/teamAssets/remove";
import route6 from "./routes/account/teamAssets/save";
import route7 from "./routes/account/teamAssets/upload";
import route8 from "./routes/account/teams/acceptInvite";
import route9 from "./routes/account/teams/create";
import route10 from "./routes/account/teams/invite";
import route11 from "./routes/account/teams/list";
import route12 from "./routes/account/teams/members";
import route13 from "./routes/account/teams/removeMember";
import route14 from "./routes/account/teams/save";
import route15 from "./routes/admin/adjustCredits";
import route16 from "./routes/admin/audit";
import route17 from "./routes/admin/grantCredits";
import route18 from "./routes/admin/platform/get";
import route19 from "./routes/admin/platform/initializeCatalog";
import route20 from "./routes/admin/platform/publishPrices";
import route21 from "./routes/admin/platform/saveModel";
import route22 from "./routes/admin/platform/saveProvider";
import route23 from "./routes/admin/users/list";
import route24 from "./routes/admin/users/password";
import route25 from "./routes/admin/users/projects";
import route26 from "./routes/admin/users/save";
import route27 from "./routes/agent";
import route28 from "./routes/agent/answer";
import route29 from "./routes/agent/canvasResult";
import route30 from "./routes/agent/create";
import route31 from "./routes/agent/get";
import route32 from "./routes/agent/list";
import route33 from "./routes/agent/mentionSource";
import route34 from "./routes/agent/message";
import route35 from "./routes/agent/rename";
import route36 from "./routes/agent/skills";
import route37 from "./routes/agents/a2a/get";
import route38 from "./routes/agents/a2a/save";
import route39 from "./routes/agents/connect";
import route40 from "./routes/agents/get";
import route41 from "./routes/agents/install";
import route42 from "./routes/agents/read";
import route43 from "./routes/agents/save";
import route44 from "./routes/agents/setEnabled";
import route45 from "./routes/agents/uninstall";
import route46 from "./routes/ai/capabilities";
import route47 from "./routes/ai/generate";
import route48 from "./routes/ai/media/generate";
import route49 from "./routes/ai/media/models";
import route50 from "./routes/ai/models";
import route51 from "./routes/assets/list";
import route52 from "./routes/assets/mkdir";
import route53 from "./routes/assets/read";
import route54 from "./routes/assets/remove";
import route55 from "./routes/assets/rename";
import route56 from "./routes/assets/save";
import route57 from "./routes/auth/invitation";
import route58 from "./routes/auth/login";
import route59 from "./routes/auth/logout";
import route60 from "./routes/auth/me";
import route61 from "./routes/auth/password";
import route62 from "./routes/auth/profile";
import route63 from "./routes/auth/register";
import route64 from "./routes/auth/setup";
import route65 from "./routes/auth/setupStatus";
import route66 from "./routes/billing/ledger";
import route67 from "./routes/billing/quote";
import route68 from "./routes/billing/transfer";
import route69 from "./routes/billing/wallet";
import route70 from "./routes/desktop/clipboard/read";
import route71 from "./routes/desktop/clipboard/write";
import route72 from "./routes/desktop/devtools";
import route73 from "./routes/desktop/openUrl";
import route74 from "./routes/desktop/plugins/install";
import route75 from "./routes/desktop/providerFile/read";
import route76 from "./routes/desktop/providerFile/select";
import route77 from "./routes/desktop/ready";
import route78 from "./routes/desktop/saveFile";
import route79 from "./routes/desktop/selectDirectory";
import route80 from "./routes/desktop/selectSaveFile";
import route81 from "./routes/desktop/update/apply";
import route82 from "./routes/desktop/update/check";
import route83 from "./routes/desktop/update/download";
import route84 from "./routes/desktop/update/index";
import route85 from "./routes/ffmpeg/cancel";
import route86 from "./routes/ffmpeg/download";
import route87 from "./routes/ffmpeg/events";
import route88 from "./routes/ffmpeg/execute";
import route89 from "./routes/ffmpeg/progress";
import route90 from "./routes/ffmpeg/status";
import route91 from "./routes/mcp/control/events";
import route92 from "./routes/mcp/control/result";
import route93 from "./routes/mcp/control/state";
import route94 from "./routes/mcp/skill";
import route95 from "./routes/mcp/status";
import route96 from "./routes/nodes/files";
import route97 from "./routes/nodes/get";
import route98 from "./routes/nodes/install";
import route99 from "./routes/nodes/save";
import route100 from "./routes/nodes/setEnabled";
import route101 from "./routes/nodes/uninstall";
import route102 from "./routes/plugins/export";
import route103 from "./routes/providers/debug/inspect";
import route104 from "./routes/providers/debug/run";
import route105 from "./routes/providers/media/add";
import route106 from "./routes/providers/media/delete";
import route107 from "./routes/providers/media/list";
import route108 from "./routes/providers/media/models";
import route109 from "./routes/providers/media/save";
import route110 from "./routes/providers/models";
import route111 from "./routes/settings/get";
import route112 from "./routes/settings/personalization/get";
import route113 from "./routes/settings/personalization/save";
import route114 from "./routes/settings/save";
import route115 from "./routes/settings/systemPrompt";
import route116 from "./routes/skills/create";
import route117 from "./routes/skills/get";
import route118 from "./routes/skills/install";
import route119 from "./routes/skills/list";
import route120 from "./routes/skills/move";
import route121 from "./routes/skills/order";
import route122 from "./routes/skills/read";
import route123 from "./routes/skills/save";
import route124 from "./routes/skills/uninstall";
import route125 from "./routes/tools/client";
import route126 from "./routes/tools/get";
import route127 from "./routes/tools/install";
import route128 from "./routes/tools/renderers";
import route129 from "./routes/tools/save";
import route130 from "./routes/tools/setEnabled";
import route131 from "./routes/tools/uninstall";
import route132 from "./routes/workspaces/check";
import route133 from "./routes/workspaces/files/list";
import route134 from "./routes/workspaces/files/mkdir";
import route135 from "./routes/workspaces/files/read";
import route136 from "./routes/workspaces/files/remove";
import route137 from "./routes/workspaces/files/rename";
import route138 from "./routes/workspaces/files/write";
import route139 from "./routes/workspaces/list";
import route140 from "./routes/workspaces/selectDirectory";

export default (app: Express) => {
  app.use("/api/account/teamAssets/copy", route1);
  app.use("/api/account/teamAssets/import", route2);
  app.use("/api/account/teamAssets/list", route3);
  app.use("/api/account/teamAssets/read", route4);
  app.use("/api/account/teamAssets/remove", route5);
  app.use("/api/account/teamAssets/save", route6);
  app.use("/api/account/teamAssets/upload", route7);
  app.use("/api/account/teams/acceptInvite", route8);
  app.use("/api/account/teams/create", route9);
  app.use("/api/account/teams/invite", route10);
  app.use("/api/account/teams/list", route11);
  app.use("/api/account/teams/members", route12);
  app.use("/api/account/teams/removeMember", route13);
  app.use("/api/account/teams/save", route14);
  app.use("/api/admin/adjustCredits", route15);
  app.use("/api/admin/audit", route16);
  app.use("/api/admin/grantCredits", route17);
  app.use("/api/admin/platform/get", route18);
  app.use("/api/admin/platform/initializeCatalog", route19);
  app.use("/api/admin/platform/publishPrices", route20);
  app.use("/api/admin/platform/saveModel", route21);
  app.use("/api/admin/platform/saveProvider", route22);
  app.use("/api/admin/users/list", route23);
  app.use("/api/admin/users/password", route24);
  app.use("/api/admin/users/projects", route25);
  app.use("/api/admin/users/save", route26);
  app.use("/api/agent", route27);
  app.use("/api/agent/answer", route28);
  app.use("/api/agent/canvasResult", route29);
  app.use("/api/agent/create", route30);
  app.use("/api/agent/get", route31);
  app.use("/api/agent/list", route32);
  app.use("/api/agent/mentionSource", route33);
  app.use("/api/agent/message", route34);
  app.use("/api/agent/rename", route35);
  app.use("/api/agent/skills", route36);
  app.use("/api/agents/a2a/get", route37);
  app.use("/api/agents/a2a/save", route38);
  app.use("/api/agents/connect", route39);
  app.use("/api/agents/get", route40);
  app.use("/api/agents/install", route41);
  app.use("/api/agents/read", route42);
  app.use("/api/agents/save", route43);
  app.use("/api/agents/setEnabled", route44);
  app.use("/api/agents/uninstall", route45);
  app.use("/api/ai/capabilities", route46);
  app.use("/api/ai/generate", route47);
  app.use("/api/ai/media/generate", route48);
  app.use("/api/ai/media/models", route49);
  app.use("/api/ai/models", route50);
  app.use("/api/assets/list", route51);
  app.use("/api/assets/mkdir", route52);
  app.use("/api/assets/read", route53);
  app.use("/api/assets/remove", route54);
  app.use("/api/assets/rename", route55);
  app.use("/api/assets/save", route56);
  app.use("/api/auth/invitation", route57);
  app.use("/api/auth/login", route58);
  app.use("/api/auth/logout", route59);
  app.use("/api/auth/me", route60);
  app.use("/api/auth/password", route61);
  app.use("/api/auth/profile", route62);
  app.use("/api/auth/register", route63);
  app.use("/api/auth/setup", route64);
  app.use("/api/auth/setupStatus", route65);
  app.use("/api/billing/ledger", route66);
  app.use("/api/billing/quote", route67);
  app.use("/api/billing/transfer", route68);
  app.use("/api/billing/wallet", route69);
  app.use("/api/desktop/clipboard/read", route70);
  app.use("/api/desktop/clipboard/write", route71);
  app.use("/api/desktop/devtools", route72);
  app.use("/api/desktop/openUrl", route73);
  app.use("/api/desktop/plugins/install", route74);
  app.use("/api/desktop/providerFile/read", route75);
  app.use("/api/desktop/providerFile/select", route76);
  app.use("/api/desktop/ready", route77);
  app.use("/api/desktop/saveFile", route78);
  app.use("/api/desktop/selectDirectory", route79);
  app.use("/api/desktop/selectSaveFile", route80);
  app.use("/api/desktop/update/apply", route81);
  app.use("/api/desktop/update/check", route82);
  app.use("/api/desktop/update/download", route83);
  app.use("/api/desktop/update", route84);
  app.use("/api/ffmpeg/cancel", route85);
  app.use("/api/ffmpeg/download", route86);
  app.use("/api/ffmpeg/events", route87);
  app.use("/api/ffmpeg/execute", route88);
  app.use("/api/ffmpeg/progress", route89);
  app.use("/api/ffmpeg/status", route90);
  app.use("/api/mcp/control/events", route91);
  app.use("/api/mcp/control/result", route92);
  app.use("/api/mcp/control/state", route93);
  app.use("/api/mcp/skill", route94);
  app.use("/api/mcp/status", route95);
  app.use("/api/nodes/files", route96);
  app.use("/api/nodes/get", route97);
  app.use("/api/nodes/install", route98);
  app.use("/api/nodes/save", route99);
  app.use("/api/nodes/setEnabled", route100);
  app.use("/api/nodes/uninstall", route101);
  app.use("/api/plugins/export", route102);
  app.use("/api/providers/debug/inspect", route103);
  app.use("/api/providers/debug/run", route104);
  app.use("/api/providers/media/add", route105);
  app.use("/api/providers/media/delete", route106);
  app.use("/api/providers/media/list", route107);
  app.use("/api/providers/media/models", route108);
  app.use("/api/providers/media/save", route109);
  app.use("/api/providers/models", route110);
  app.use("/api/settings/get", route111);
  app.use("/api/settings/personalization/get", route112);
  app.use("/api/settings/personalization/save", route113);
  app.use("/api/settings/save", route114);
  app.use("/api/settings/systemPrompt", route115);
  app.use("/api/skills/create", route116);
  app.use("/api/skills/get", route117);
  app.use("/api/skills/install", route118);
  app.use("/api/skills/list", route119);
  app.use("/api/skills/move", route120);
  app.use("/api/skills/order", route121);
  app.use("/api/skills/read", route122);
  app.use("/api/skills/save", route123);
  app.use("/api/skills/uninstall", route124);
  app.use("/api/tools/client", route125);
  app.use("/api/tools/get", route126);
  app.use("/api/tools/install", route127);
  app.use("/api/tools/renderers", route128);
  app.use("/api/tools/save", route129);
  app.use("/api/tools/setEnabled", route130);
  app.use("/api/tools/uninstall", route131);
  app.use("/api/workspaces/check", route132);
  app.use("/api/workspaces/files/list", route133);
  app.use("/api/workspaces/files/mkdir", route134);
  app.use("/api/workspaces/files/read", route135);
  app.use("/api/workspaces/files/remove", route136);
  app.use("/api/workspaces/files/rename", route137);
  app.use("/api/workspaces/files/write", route138);
  app.use("/api/workspaces/list", route139);
  app.use("/api/workspaces/selectDirectory", route140);
}
