/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./../components/settings/panels/about.vue')['default']
    Agent: typeof import('./../components/agent/index.vue')['default']
    AttachmentList: typeof import('./../components/agent/attachmentList.vue')['default']
    AttachmentPreview: typeof import('./../components/agent/attachmentPreview.vue')['default']
    CanvasShortcuts: typeof import('./../components/settings/panels/general/canvasShortcuts.vue')['default']
    Conversation: typeof import('./../components/agent/conversation.vue')['default']
    Developer: typeof import('./../components/settings/panels/developer/index.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    Ffmpeg: typeof import('./../components/settings/panels/pluginMarket/ffmpeg.vue')['default']
    FfmpegRequired: typeof import('./../components/settings/ffmpegRequired.vue')['default']
    General: typeof import('./../components/settings/panels/general/index.vue')['default']
    IconBorderRadius: typeof import('@tabler/icons-vue')['IconBorderRadius']
    IconExternalLink: typeof import('@tabler/icons-vue')['IconExternalLink']
    IconKey: typeof import('@tabler/icons-vue')['IconKey']
    IconLogin: typeof import('@tabler/icons-vue')['IconLogin']
    IconMovie: typeof import('@tabler/icons-vue')['IconMovie']
    IconSearch: typeof import('@tabler/icons-vue')['IconSearch']
    IconTextSize: typeof import('@tabler/icons-vue')['IconTextSize']
    KeyInput: typeof import('./../components/settings/panels/general/keyInput.vue')['default']
    LanguageModel: typeof import('./../components/settings/panels/languageModel/index.vue')['default']
    MarkdownImage: typeof import('./../components/markdownImage.vue')['default']
    Mcp: typeof import('./../components/settings/panels/mcp/index.vue')['default']
    MediaModel: typeof import('./../components/settings/panels/mediaModel/index.vue')['default']
    MentionContent: typeof import('./../components/agent/mentionContent.vue')['default']
    MentionMenu: typeof import('./../components/agent/mentionMenu.vue')['default']
    MentionThumbnail: typeof import('./../components/agent/mentionThumbnail.vue')['default']
    Menu: typeof import('./../components/agent/menu.vue')['default']
    MessageMarkdown: typeof import('./../components/messageMarkdown.vue')['default']
    ModelPopover: typeof import('./../components/modelPopover.vue')['default']
    Personalization: typeof import('./../components/settings/panels/personalization.vue')['default']
    PluginMarket: typeof import('./../components/settings/panels/pluginMarket/index.vue')['default']
    Privacy: typeof import('./../components/settings/panels/privacy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./../components/settings/index.vue')['default']
    SkillMenu: typeof import('./../components/agent/skillMenu.vue')['default']
    TfAccount: typeof import('./../components/settings/tfAccount.vue')['default']
    TfRechargeDialog: typeof import('./../components/settings/tfRechargeDialog.vue')['default']
    ToolMessage: typeof import('./../components/agent/toolMessage.vue')['default']
    Ui: typeof import('./../components/settings/panels/ui.vue')['default']
    UpdateBox: typeof import('./../components/updateBox.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
